DEBUG = False
SQLALCHEMY_ECHO = False
SECRET_KEY = 'Sm9obiBTY2hyb20ga2lja3MgYXNz'
STRIPE_API_KEY = 'SmFjb2IgS2FwbGFuLU1vc3MgaXMgYSBoZXJv'
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/messenger.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SERVER_NAME = 'localhost:5000'
